### ISSUE TITLE
Nice to have features for commercial imagery query

### ISSUE THREAD

**Issue by fangfy** [sentinel-hub/odc-sh#4]
In the commercial_data.ipynb:
* `odc_sh` needs to be installed for the notebook to run. I suppose this is a depency for other notebooks as well, but I don't see this mentioned in the README file.
* after constructing the bounding box for the query, it will be really nice to be able to visualize the location on a map. e.g. the display_map function we have in deafrica sandbox: https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/main/Datasets/Water_Observations_from_Space.ipynb
* it will also be handy to see the size of the area queried.

**Comment by masaarnez** [comment]
We updated the README file and added new features to the example notebook for commercial data [commercial_data.ipynb](https://github.com/sentinel-hub/odc-sh/blob/master/notebooks/commercial_data.ipynb):

- visualization of the search area for commercial data
- area calculation for bounding box
